# Generated by Django 4.2.3 on 2023-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('str_cha', '0002_alter_producto_options_alter_producto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
