# Generated by Django 4.2.3 on 2023-08-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('str_cha', '0008_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
